FROM ubuntu:16.04
MAINTAINER Christian Schroeder de Witt

# Ubuntu Packages
RUN apt-get update -y && apt-get install software-properties-common -y && \
    add-apt-repository -y multiverse && apt-get update -y && apt-get upgrade -y && \
    apt-get install -y apt-utils nano vim man build-essential wget sudo && \
    rm -rf /var/lib/apt/lists/*

# Install curl and other dependencies
RUN apt-get update -y && apt-get install -y curl libssl-dev openssl libopenblas-dev \
    libhdf5-dev hdf5-helpers hdf5-tools libhdf5-serial-dev libprotobuf-dev protobuf-compiler git
RUN curl -sk https://raw.githubusercontent.com/torch/distro/master/install-deps | bash && \
    rm -rf /var/lib/apt/lists/*

#Install python3 pip3
RUN apt-get update
RUN apt-get -y install python3
RUN apt-get update && apt-get install -y python3-pip

# RUN mkdir /install
# WORKDIR /install

#### -------------------------------------------------------------------
#### install tensorflow
#### -------------------------------------------------------------------
RUN pip3 install --upgrade tensorflow
RUN pip3 install sacred pymongo pyyaml
RUN mkdir /install 
WORKDIR /install

#### -------------------------------------------------------------------
#### install mujoco
#### -------------------------------------------------------------------
RUN add-apt-repository ppa:jamesh/snap-support && apt-get update && apt install -y patchelf
RUN apt install -y libosmesa6-dev libglew1.5-dev
# RUN add-apt-repository ppa:jamesh/snap-support && apt-get update && apt install -y patchelf
RUN mkdir -p /root/.mujoco \
    && wget https://www.roboti.us/download/mjpro150_linux.zip -O mujoco.zip \
    && unzip mujoco.zip -d /root/.mujoco \
    && rm mujoco.zip
RUN export PATH=$PATH:$HOME/.local/bin
COPY ./mujoco_key.txt /root/.mujoco/mjkey.txt
ENV LD_LIBRARY_PATH /root/.mujoco/mjpro150/bin:${LD_LIBRARY_PATH}

RUN pip3 install gym[mujoco] --upgrade
RUN pip3 install mujoco-py
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mjpro150/bin" >> ~/.bashrc
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mjpro150/bin" >> ~/.profile
RUN python3 -c "import mujoco_py"

RUN apt-get install -y libhdf5-serial-dev
RUN pip3 install numpy sklearn h5py gym cffi setproctitle matplotlib

EXPOSE 8888

WORKDIR /icnn
